In [8]:
from scipy.stats import entropy
from collections import Counter
import math
import matplotlib
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import time
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
import warnings# warning filter
import os #paths to file
warnings.filterwarnings("ignore")



In [9]:
df=pd.read_csv('/content/drive/MyDrive/machine learning/ML_FDS PROJECT/loan-train.csv')
df=df.dropna(axis=0)
df.fillna(df.mean(),inplace=True)
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
5    LP001011    Male     Yes          2      Graduate           Yes   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
5               5417             4196.0       267.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
5               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[480 rows x 13 columns]

In [17]:
x=df[['ApplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History']].astype(float)
y=df['Loan_Status'].astype(str)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

In [25]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train) 
x_test = sc_x.transform(x_test)
  
print (x_train[0:100, :])

[[ 4.07326479e-01 -7.39953152e-01  2.59060651e-01  4.23021712e-01]
 [-3.34212615e-01 -4.18487057e-01  2.59060651e-01  4.23021712e-01]
 [-4.72034947e-01 -7.87577759e-01  2.59060651e-01  4.23021712e-01]
 [-8.48413542e-01  1.10550036e+00  2.59060651e-01  4.23021712e-01]
 [-1.05958686e-01  5.77590096e-02  2.59060651e-01  4.23021712e-01]
 [ 5.94142132e-01  4.03037408e-01  2.59060651e-01  4.23021712e-01]
 [-6.04362701e-01 -2.99425540e-01  2.59060651e-01  4.23021712e-01]
 [ 1.30362952e+00 -7.51859304e-01  2.59060651e-01  4.23021712e-01]
 [-8.06746326e-01 -4.66111664e-01  2.59060651e-01  4.23021712e-01]
 [ 3.24596286e+00  5.40362111e+00  2.59060651e-01  4.23021712e-01]
 [-7.19062018e-01 -9.06639275e-01  2.59060651e-01  4.23021712e-01]
 [-6.46258859e-01 -6.68516242e-01 -2.68826594e+00 -2.36394486e+00]
 [-1.65483281e-01 -1.56551720e-01  2.59060651e-01 -2.36394486e+00]
 [-5.12099579e-01 -8.94733124e-01  2.22394505e+00  4.23021712e-01]
 [-6.04362701e-01 -6.08985484e-01  2.59060651e-01  4.23021712e

In [26]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [27]:
y_pred = classifier.predict(x_test)


In [28]:

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[18 31]
 [ 0 95]]


In [29]:
from sklearn.metrics import accuracy_score
a=accuracy_score(y_test, y_pred)
print ("Accuracy : ",100*a )


Accuracy :  78.47222222222221
